return {
	-- "nvim-tree/nvim-tree.lua",
	-- dependencies = {
	-- 	"nvim-tree/nvim-web-devicons",
	-- },
	-- config = function()
	-- 	local nvimtree = require("nvim-tree")
	-- 	local width = 35
	-- 	-- local height = 60
	-- 	-- local HEIGHT_RATIO = 0.8 -- You can change this
	-- 	-- local WIDTH_RATIO = 0.5 -- You can change this too
	--
	-- 	-- recommended settings from nvim-tree documentation
	-- 	vim.g.loaded_netrw = 1
	-- 	vim.g.loaded_netrwPlugin = 1
	--
	-- 	-- change color for arrows in tree to light blue
	-- 	vim.cmd([[ highlight NvimTreeFolderArrowClosed guifg=#3FC5FF ]])
	-- 	vim.cmd([[ highlight NvimTreeFolderArrowOpen guifg=#3FC5FF ]])
	--
	-- 	-- configure nvim-tree
	-- 	nvimtree.setup({
	-- 		disable_netrw = true,
	-- 		hijack_netrw = true,
	-- 		respect_buf_cwd = true,
	-- 		sync_root_with_cwd = true,
	-- 		view = {
	-- 			relativenumber = false,
	-- 			-- width = width,
	-- 			adaptive_size = true,
	-- 		},
	-- 		-- change folder arrow icons
	-- 		renderer = {
	-- 			-- indent_markers = {
	-- 			-- 	enable = true,
	-- 			-- },
	-- 			icons = {
	-- 				glyphs = {
	-- 					folder = {
	-- 						arrow_closed = "", -- arrow when folder is closed
	-- 						arrow_open = "", -- arrow when folder is open
	-- 					},
	-- 				},
	-- 			},
	-- 		},
	-- 		-- disable window_picker for
	-- 		-- explorer to work well with
	-- 		-- window splits
	-- 		actions = {
	-- 			open_file = {
	-- 				quit_on_open = false,
	-- 				-- window_picker = {
	-- 				-- 	enable = false,
	-- 				-- },
	-- 			},
	-- 		},
	-- 		filters = {
	-- 			custom = { ".DS_Store" },
	-- 		},
	-- 		git = {
	-- 			enable = true,
	-- 			ignore = false,
	-- 		},
	-- 	})
	--
	-- 	-- set keymaps
	-- 	local keymap = vim.keymap -- for conciseness
	--
	-- 	keymap.set("n", "<leader>ee", "<cmd>NvimTreeToggle<CR>", { desc = "Toggle file explorer" }) -- toggle file explorer
	-- 	keymap.set(
	-- 		"n",
	-- 		"<leader>ef",
	-- 		"<cmd>NvimTreeFindFileToggle<CR>",
	-- 		{ desc = "Toggle file explorer on current file" }
	-- 	) -- toggle file explorer on current file
	-- 	-- keymap.set("n", "<leader>ec", "<cmd>NvimTreeCollapse<CR>", { desc = "Collapse file explorer" }) -- collapse file explorer
	-- 	-- keymap.set("n", "<leader>er", "<cmd>NvimTreeRefresh<CR>", { desc = "Refresh file explorer" }) -- refresh file explorer
	-- end,
}
