set -ga terminal-overrides ",xterm-termite:Tc"

run-shell "powerline-daemon -q"

source /usr/lib/python3.7/site-packages/powerline/bindings/tmux/powerline.conf


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

#free original ctrl-b prefix keybinding.
unbind C-b

#set prefix to ctrl-a
set -g prefix C-a

#vi keys for switching panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

#splitting panes
bind - split-window -v
bind | split-window -h

#shift movement keys will resize panes
bind J resize-pane -L 5
bind K resize-pane -D 5
bind H resize-pane -D 5
bind L resize-pane -D 5

#start tabs at index 1
set -g base-index 1

#make pane numbering consistent with windows
set -g pane-base-index 1

# Renumber windows when a window is closed
# This guarantees it will be easier for you to switch
# between windows as you keep opening and closing them
set -g renumber-windows on

# Automatically set window title according to the running program
set-window-option -g automatic-rename on
set-option -g set-titles on

run -b '~/.tmux/plugins/tpm/tpm'

